version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Branch: $CODEBUILD_SOURCE_VERSION"
      - if [[ "$CODEBUILD_SOURCE_VERSION" == *"refs/heads/dev"* ]]; then
          echo "Building for DEV branch";
          npm run build;
        elif [[ "$CODEBUILD_SOURCE_VERSION" == *"refs/heads/uat"* ]]; then
          echo "Building for UAT branch";
          npm run build;
        elif [[ "$CODEBUILD_SOURCE_VERSION" == *"refs/heads/master"* ]]; then
          echo "Building for PROD branch";
          npm run build;
        else
          echo "Branch not recognized. Skipping build.";
          exit 1;
        fi

  post_build:
    commands:
      - echo "Post build started"
      - if [[ "$CODEBUILD_SOURCE_VERSION" == *"refs/heads/dev"* ]]; then
          echo "Deploying to sample-react-dev";
          aws s3 sync build/ s3://sample-react-dev --delete;
        elif [[ "$CODEBUILD_SOURCE_VERSION" == *"refs/heads/uat"* ]]; then
          echo "Deploying to sample-react-uat";
          aws s3 sync build/ s3://sample-react-uat --delete;
        elif [[ "$CODEBUILD_SOURCE_VERSION" == *"refs/heads/master"* ]]; then
          echo "Deploying to sample-react-prod";
          aws s3 sync build/ s3://sample-react-prod --delete;
        else
          echo "No matching branch for deployment";
          exit 1;
        fi

artifacts:
  files:
    - '**/*'

        





